name: json-validation
version: 0.1.0.0
description: JSON schema validation
synopsis: Lightweight combinators for validating JSON
maintainer: Mitchell Rosen
license: BSD3
github: mitchellwrosen/json-validation
category: Data

ghc-options: -Wall

default-extensions:
  - BangPatterns
  - DeriveDataTypeable
  - DeriveFoldable
  - DeriveGeneric
  - FlexibleContexts
  - FlexibleInstances
  - GADTs
  - InstanceSigs
  - LambdaCase
  - MultiParamTypeClasses
  - NoImplicitPrelude
  - OverloadedLists
  - OverloadedStrings
  - ScopedTypeVariables
  - StandaloneDeriving
  - TupleSections
  - TypeFamilies
  - ViewPatterns

dependencies:
  - aeson
  - base >= 4.7 && < 5
  - base-compat >= 0.9.1
  - containers
  - hashable
  - iso8601-time
  - microlens            >= 0.3.0.0 && < 0.4.8
  - mtl
  - pcre-light
  - scientific
  - text
  - unordered-containers >= 0.2.6.0 && < 0.2.8
  - vector               >= 0.11    && < 0.12

when:
  condition: impl(ghc < 8.0.1)
  dependencies:
    - semigroups

library:
  source-dirs: src
  other-modules:
    - Data.Aeson.Validation.Internal

tests:
  doctest:
    main: DocTest.hs
    source-dirs: test
    dependencies:
      - doctest >= 0.11.0
      - json-validation
      - quickcheck-instances

  spec:
    main: Spec.hs
    source-dirs:
      # Add src/ as a source dir rather than depend on the library so we can
      # test functions in the .Internal modules without exporting them.
      # Unfortunately, this means we have to duplicate all of its dependencies.
      - src
      - test
    dependencies:
      - hspec
      - json-validation
      - QuickCheck
      - quickcheck-text
