name: json-validation
version: 0.1.0.0

ghc-options: -Wall

default-extensions:
  - BangPatterns
  - DeriveAnyClass
  - DeriveDataTypeable
  - DeriveFoldable
  - DeriveGeneric
  - FlexibleInstances
  - GADTs
  - InstanceSigs
  - LambdaCase
  - MultiParamTypeClasses
  - OverloadedLists
  - OverloadedStrings
  - StandaloneDeriving
  - TupleSections
  - TypeFamilies
  - ViewPatterns

dependencies:
  - base

library:
  source-dirs: src
  other-modules:
    - Data.Aeson.Validation.Internal
  dependencies:
    - aeson
    - containers
    - hashable
    - iso8601-time
    - microlens
    - mtl
    - pcre-light
    - scientific
    - text
    - unordered-containers
    - vector

tests:
  doctest:
    main: DocTest.hs
    source-dirs: test
    dependencies:
      - doctest
      - json-validation
      - quickcheck-instances

  spec:
    main: Spec.hs
    source-dirs:
      # Add src/ as a source dir rather than depend on the library so we can
      # test functions in the .Internal modules without exporting them.
      # Unfortunately, this means we have to duplicate all of its dependencies.
      - src
      - test
    dependencies:
      - aeson
      - hspec
      - QuickCheck
      - quickcheck-text
      - scientific
      - text
      # Inherited from library
      - containers
      - hashable
      - iso8601-time
      - microlens
      - mtl
      - pcre-light
      - unordered-containers
      - vector
