name: json-validation
version: 0.1.0.0

ghc-options: -Wall

dependencies:
  - base

library:
  source-dirs: src
  other-modules:
    - Data.Aeson.Validation.Types
  dependencies:
    - aeson
    - containers
    - microlens
    - mtl
    - pcre-light
    - scientific
    - text
    - unordered-containers
    - vector

tests:
  doctest:
    main: DocTest.hs
    source-dirs: test
    dependencies:
      - doctest
      - json-validation
      - quickcheck-instances

  spec:
    main: Spec.hs
    source-dirs: test
    dependencies:
      - hspec
      - json-validation
